name: Build and Test

on:
  pull_request:
    paths:
      - '**.go'
    branches:
      - master
  push:
    paths:
      - '**.go'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Build
        run: go build

      - name: Test
        run: go test ./...