name: Build and Test

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '**.go'
    branches:
      - main
  push:
    paths:
      - '**.go'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: go build

      - name: Test
        run: go test ./...